owncloud/docs-client-ios-app

modules/ROOT/pages/accounts.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/available_offline.adoc, modules/ROOT/pages/collaboration.adoc, modules/ROOT/pages/files.adoc, modules/ROOT/pages/files_integration.adoc, modules/ROOT/pages/quick_access.adoc, modules/ROOT/pages/security.adoc, modules/ROOT/pages/settings.adoc
Fixes to image sizes mainly in pdf, especially in tables.
=> Fixes to image sizes mainly in pdf, especially in tables

bin/manual_config
=> Update of the manual_config file for makepdf to be inline with the other repos

modules/ROOT/pages/accounts.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/available_offline.adoc, modules/ROOT/pages/collaboration.adoc, modules/ROOT/pages/files.adoc, modules/ROOT/pages/files_integration.adoc, modules/ROOT/pages/quick_access.adoc, modules/ROOT/pages/security.adoc, modules/ROOT/pages/settings.adoc
=> [11.7] [PR 4] Fixes to image sizes mainly in pdf, especially in tables

bin/manual_config
=> [11.7] [PR 3] Update of the manual_config file for makepdf to be inline with the other repos

modules/ROOT/pages/accounts.adoc, modules/ROOT/pages/appendices/mdm.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/collaboration.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/files.adoc, modules/ROOT/pages/files_integration.adoc, modules/ROOT/pages/quick_access.adoc, modules/ROOT/pages/security.adoc, modules/ROOT/pages/settings.adoc
This PR fixes various issues:
* Headline capitalisation
* toc
* page-aliases
=> Fix various issues

modules/ROOT/pages/accounts.adoc, modules/ROOT/pages/appendices/mdm.adoc, modules/ROOT/pages/appendices/troubleshooting.adoc, modules/ROOT/pages/collaboration.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/files.adoc, modules/ROOT/pages/files_integration.adoc, modules/ROOT/pages/quick_access.adoc, modules/ROOT/pages/security.adoc, modules/ROOT/pages/settings.adoc
=> [11.7] [PR 11] Fix various issues

modules/ROOT/nav.adoc, modules/ROOT/pages/appendices/release_notes.adoc
=> [11.7] [PR 13] Using release notes

bin/makepdf, lib/extensions/remote-include-processor.js, site.yml
=> [11.7] [PR 18] Prepare the repo to include .adoc files from an URI

.drone.star
=> [11.7] [PR 20] cancel previous builds

docs/new-version-branch.md
This is just a text addon to the branching documentation to be inline with docs.
* Adds a PR text proposal
* Text fixes
Backport to 11.7 and 11.8
=> Update new version branch text (add PR text suggestion)

docs/new-version-branch.md
=> [11.7] [PR 25] Update new version branch text (add PR text suggestion)

docs/new-version-branch.md
=> [11.8] [PR 25] Update new version branch text (add PR text suggestion)

docs/new-version-branch.md
Minor typo fixes
Backport to 11.8 and 11.7
=> Text fixes in the new version branch description

docs/new-version-branch.md
=> [11.8] [PR 31] Text fixes in the new version branch description

docs/new-version-branch.md
=> [11.7] [PR 31] Text fixes in the new version branch description

bin/makepdf
=> [11.8] [PR 37] Fix for makepdf refs #34

bin/makepdf
=> [11.7] [PR 37] Fix for makepdf refs #34

README.md, docs/the-branching-workflow.md
These are just minor repo text fixes outside antora.
Backport to 11.8 and 11.7
=> Minor text fixes

README.md, docs/the-branching-workflow.md
=> [11.8] [PR 43] Minor text fixes

README.md, docs/the-branching-workflow.md
=> [11.7] [PR 43] Minor text fixes

docs/the-branching-workflow.md
References: #43 
One fix missed, already fixed in the backports of 43
=> Missed one text fix

README.md, package.json, yarn.lock
=> [11.8][PR 47] Add Antora Site Structure Description for Docs

README.md, package.json, yarn.lock
=> [11.7] [PR 47] Add Antora Site Structure Description for Docs

site.yml
=> [11.7] [PR 50] site.yml attribute fix

.drone.star, .prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [11.8] [PR 53] Updates deployment files to be in sync with docs

.drone.star, .prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [11.7] [PR 53] Updates deployment files to be in sync with docs

docs/new-version-branch.md
=> [11.8] [PR 59] update of the new version branch documentation

docs/new-version-branch.md
=> [11.7] [PR 59] update of the new version branch documentation

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [11.7] [PR 15] Improve crash log description

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [11.8] [PR 15] Improve crash log description

package.json
=> [11.8] [PR 67] adding a build command for staging

package.json
=> [11.7] [PR 67] adding a build command for staging

site.yml
=> [11.8] [PR 71] Harmonize site.yml to be inline with docs

site.yml
=> [11.7] [PR 71] Harmonize site.yml to be inline with docs

site.yml
=> [11.7] [PR 74] Add start_page in site.yml

site.yml
=> [11.8] [PR 74] Add start_page in site.yml

modules/ROOT/pages/appendices/troubleshooting.adoc
This PR fixes an internal broken link.
Backport to 11.8 and 11.7
=> Fix broken internal link

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [11.8] [PR 77] Fix broken internal link

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [11.7] [PR 77] Fix broken internal link

docs/new-version-branch.md
=> [11.8] [PR 83] branching text fix

docs/new-version-branch.md
=> [11.9] [PR 83] branching text fix

docs/new-version-branch.md
=> [11.10] [PR 83] branching text fix

modules/ROOT/pages/appendices/mdm_tables.adoc
=> [11.10] [PR 89] fix: fix deprecated urls

modules/ROOT/pages/appendices/mdm_tables.adoc
=> [11.9] [PR 89] fix: fix deprecated urls

modules/ROOT/pages/appendices/mdm.adoc
=> [11.10] [PR 96] remove Licensing dummy text

modules/ROOT/pages/files.adoc
fixes issue #118 
Backports to 11.11 and 11.10
=> explaining file size differences on different systems

modules/ROOT/pages/files.adoc
=> [11.11] [PR 126] explaining file size differences on different systems

modules/ROOT/pages/files.adoc
=> [11.10] [PR 126] explaining file size differences on different systems

modules/ROOT/pages/appendices/mdm.adoc
Just two broken links to fix.
Backport to 11.11 and 12.0
=> Fix broken links

modules/ROOT/pages/appendices/mdm.adoc
=> [11.11] [PR 142] Fix broken links

modules/ROOT/pages/appendices/mdm.adoc
=> [12.0] [PR 142] Fix broken links

modules/ROOT/pages/appendices/mdm.adoc
=> [12.0] [PR 147] Add MDM parameter for File Provider / Files.app (file provider.browseable)

.drone.star, site.yml
=> [11.11] [PR 154] Update site.yml

modules/ROOT/pages/appendices/mdm.adoc
=> Show 3rd level sections in MDM toc

modules/ROOT/pages/appendices/mdm.adoc
=> [12.0] [PR 159] Show 3rd level sections in MDM toc

modules/ROOT/pages/appendices/mdm.adoc
=> [11.11] [PR 159] Show 3rd level sections in MDM toc

.gitignore, README.md, bin/prepare_site_yml
=> [11.11] [PR 167] Update readme and prepare dev env

.gitignore, README.md, bin/prepare_site_yml
=> [12.0] [PR 167] Update readme and prepare dev env

package.json
=> [12.0] [PR 170] Update package.json

package.json
=> [11.11] [PR 170] Update package.json

modules/ROOT/pages/appendices/troubleshooting.adoc
(now lists HTTP logging)
---
Can be back ported to all versions.
=> Improve Troubleshooting TOC

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [12.0] [PR 174] Improve Troubleshooting TOC

modules/ROOT/pages/appendices/troubleshooting.adoc
=> [11.11] [PR 174] Improve Troubleshooting TOC

docs/new-version-branch.md
=> [11.11] [PR 185] Just a small internal link fix

es-docker-compose.yml
=> [12.1] [PR 189] Add ES example yml for ease of testing

es-docker-compose.yml
=> [12.0] [PR 189] Add ES example yml for ease of testing

ext-antora/generate-index.js
Fix a edge case for search index generation.
Backport to 12.1 and 12.0
=> Fix a edge case for search index generation.

ext-antora/generate-index.js
=> [12.1] [PR 193] Fix a edge case for search index generation.

ext-antora/generate-index.js
=> [12.0] [PR 193] Fix a edge case for search index generation.

docs/new-version-branch.md, ext-antora/generate-index.js
Script update for consistency + small fixes.
Backport to 12.1 and 12.0
=> Es index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [12.1] [PR 196] Es index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [12.0] [PR 196] Es index update

modules/ROOT/pages/appendices/release_notes.adoc, modules/ROOT/partials/nav.adoc
=> [12.1] [PR 201] Remove release notes

modules/ROOT/pages/appendices/release_notes.adoc, modules/ROOT/partials/nav.adoc
=> [12.0] [PR 201] Remove release notes

.drone.star
=> [12.2] [PR 205] chore: report CI result to builds channel

ext-antora/generate-index.js
=> [12.2] [PR 207] Fix command typo in generate-index.js

package.json, yarn.lock
=> [12.2] [PR 216] Antora package.json refactoring

package.json, yarn.lock
=> [12.1] [PR 216] Antora package.json refactoring

ext-antora/comp-version.js
=> [12.3] [PR 230] Update antora extension to print component, versions and files

ext-antora/comp-version.js
=> [12.2] [PR 230] Update antora extension to print component, versions and files

ext-antora/comp-version.js
=> [12.2] [PR 235] Update the component-version counting extension

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [12.3] [PR 239] Update the versioning process

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [12.4] [PR 239] Update the versioning process

.drone.star
These are the changes necessary to finalize the creation of the 12.6 branch.
* The 12.6 branch is already pushed, prepared and is included in the branch protection rules.
* Note that this PR can be merged at any time but:
* must be merged **before** applying content changes and
* **before** merging the docs PR to include this version.
* Post merging this, we need to backport all relevant changes created in master to 12.6
=> Changes necessary for 12.6
