owncloud/docs-client-ios-app

.drone.star
site.yml

According the info from @hosy, a new iOS app release will be published soon.
These are the changes in this repo needed for the upcoming 11.7.1 version of the iOS app.
Post merging we need to finalize with following tasks:
* Branch protection and renaming according the process defined
* Create a new PR in docs reflecting the version change here

Changes necessary for the new iOS App 11.7.1

---

modules/ROOT/nav.adoc
modules/ROOT/pages/appendices/release_notes.adoc

Using release notes in the same way we have them in the Android docs, see : https://github.com/owncloud/docs-client-android/pull/6 (Update release notes)
Referencing the iOS version of course 😃 

Using release notes

---

bin/makepdf
lib/extensions/remote-include-processor.js
site.yml

This PR prepares the repo to include .adoc files from an URI.
For details see the comments in script: lib/extensions/remote-include-processor.js
**Necessary for:**
- Including dynamically created mdm .adoc files in the iOS repo
- https://github.com/owncloud/ios-app/issues/842 ([FEATURE REQUEST] Generate AppConfig spec file from OCClassSettings metadata automatically)
**Tests**
I have tested this by including an .adoc document from the docs repo via an URI and doing a build respectively running  makepdf - all works as expected.
The nice thing having this, we can now include any .adoc file automatically generated by a script from an external URI like another github repo, without manually maintaining static content.
**NOTE**
Any external created content, especially if created dynamically, …

Prepare the repo to include .adoc files from an URI

---

.drone.star
site.yml

These are the changes necessary to finalize the creation of the 11.8 branch.
The 11.8 branch is already pushed, prepared and is included in the branch protection rules.
Note that the 11.8 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in the ios-app is set. This means, that in the docs homepage,
`latest` will point to 11.7 until the tag in the ios-app repo is set accordingly.
Note, this PR must be merged *before* the 11.8 tag in the ios-app repo is set to avoid a 404 for `latest`. 
Against the explanation, discussion, ios-app release template and descripton ect, someone already set the tag to 11.8 in the the ios-app repo which currently leads to a 404 in the docs web page for the ios app 🤦‍♂️ 
Note, that this PR ist …

changes necessary for 11.8

---

bin/makepdf

Fixing a missed change in an attribute in makepdf.
References #34 (Fix the family directory structure)
Backport to 11.8 and 11.7

Fix for makepdf refs #34

---

.drone.star

[11.8] [PR 56] chore: replace s3 server in drone config by secret

---

.drone.star

[11.7] [PR 56] chore: replace s3 server in drone config by secret

---

modules/ROOT/pages/appendices/mdm_tables.adoc

References: https://github.com/owncloud/ios-app/pull/1094 ([docs/folder-structure] Changed Docs Structure / MDM)
This PR updates the mdm_tables for 11.7 only.
Note that the file is the 11.7 tag version.
The table is hardcoded as file an not dynamically included as it will be in master (soon).
No backport

Update the mdm table file for 11.7 only (hardcoded)

---

modules/ROOT/pages/appendices/mdm_tables.adoc

References: https://github.com/owncloud/ios-app/pull/1094 ([docs/folder-structure] Changed Docs Structure / MDM)
This PR updates the mdm_tables for 11.8 only.
Note that the file is the 11.8 tag version.
The table is hardcoded as file an not dynamically included as it will be in master (soon).
No backport

Update the mdm table file for 11.8 only (hardcoded)

---

modules/ROOT/pages/appendices/troubleshooting.adoc

Takeover from: https://github.com/owncloud/ios-app/pull/1016 ([Docs] Improve crash log description)
Improve the logging description
* Adding text
* Fixing capture description

Improve crash log description

---

.drone.star
site.yml

These are the changes necessary to finalize the creation of the 11.9 branch.
The 11.9 branch is already pushed and prepared and is included in the branch protection rules.
When 11.9 (iOS-App) is finally out, the 11.7 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-ios-app/blob/master/docs/new-version-branch.md
Note, that the 11.9 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in iOS-App repo is set. This means, that in the docs homepage,
`latest` will point to 11.8 until the tag in iOS-App repo is set accordingly. When merging this PR,
11.7 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 11.9 tag in the iOS-App repo is set to avoid …

Changes necessary for the upcoming 11.9 release

---

.drone.star
site.yml

These are the changes necessary to finalize the creation of the 11.10 branch.
The 11.10 branch is already pushed and prepared and is included in the branch protection rules.
When 11.10 (iOS-App) is finally out, the 11.8 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-ios-app/blob/master/docs/new-version-branch.md
Note, that the 11.10 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in iOS-App repo is set. This means, that in the docs homepage, `latest` will point to 11.9 until the tag in iOS-App repo is set accordingly. When merging this PR, 11.8 will be dropped from the web but is available via pdf as usual.
Note, this PR must be merged before the 11.10 tag in the iOS-App repo is set to …

Changes Necessary for 11.10

---

modules/ROOT/pages/appendices/mdm.adoc

Parameters `debugOnly`, so description isn't that important
Related issue:
https://github.com/owncloud/docs-client-ios-app/issues/95

remove Licensing dummy text

---

.drone.star
site.yml

Referencing: #114 (Release 11.11.0)
**IMPORTANT**: when 11.11 has been tagged, we need to fix the version attribute for mdm in antora.yml in the 11.11 branch. 
These are the changes necessary to finalize the creation of the 11.11 branch.
The 11.11 branch is already pushed and prepared and is included in the branch protection rules.
When 11.11 (iOS-App) is finally out, the 11.9 branch can be archived,
see step 4 in https://github.com/owncloud/docs-client-ios-app/blob/master/docs/new-version-branch.md
Note, that the 11.11 branch in this repo is already created, but the `latest` pointer on the web
will be set to it automatically when the tag in iOS-App repo is set. This means, that in the docs homepage,
`latest` will point to 11.10 until the tag in iOS-App repo is set accordingly. When …

Changes Necessary For 11.11

---

modules/ROOT/pages/accounts.adoc
modules/ROOT/pages/appendices/mdm.adoc
modules/ROOT/pages/appendices/troubleshooting.adoc
modules/ROOT/pages/available_offline.adoc
modules/ROOT/pages/collaboration.adoc
modules/ROOT/pages/faq.adoc
modules/ROOT/pages/files.adoc
modules/ROOT/pages/files_integration.adoc
modules/ROOT/pages/installation.adoc
modules/ROOT/pages/quick_access.adoc
modules/ROOT/pages/security.adoc
modules/ROOT/pages/settings.adoc
modules/ROOT/pages/task_scheduling.adoc

**This is no content change !**
When using the attribute `:description:` which creates a meta tag in htm for search engines when rendered, you need to use two rules:
* It must be under the section header, not in aprticular order, but without a blank line above
* You must not use any links or attributes like `xref:{url}[text]` - will not get resolved and taken as it is
Found by chance. This PR corrects this for the docs-client-android repo.
This will now make search engines print predefined text more likely than before when returning search results.
Additionally fixed image positions and size.
Backport to 11.11

Move and update the description attribute to the correct place

---

antora.yml

References: #146 
We no longer have to differentiate between legacy iOS app and new iOs app.

[12.0] Remove iOS version in antora.yml

---

antora.yml

We no longer have to differentiate between legacy iOS app and new iOs app.

Remove iOS version in antora.yml

---

antora.yml

References: #146 
We no longer have to differentiate between legacy iOS app and new iOs app.

[11.11] Remove iOS version in antora.yml

---

.drone.star

These are the changes necessary to finalize the creation of the 12.1 branch.
* The 12.1 branch is already pushed and prepared and is included in the branch protection rules.
* When 12.1 is finally out, the 11.11 branch can be archived, see step 3 in [Create a New Version Branch](https://github.com/owncloud/docs-client-ios-app/blob/master/docs/new-version-branch.md)
* Note, that the 12.1 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in ios is set. This means, that in the docs homepage, `latest` will point to 12.0 until the tag in ios is set accordingly. When merging this PR, 11.11 will be dropped from the web.
* Note that this PR must be merged **before** the 12.1 tag in ios is set to avoid a 404 for `latest`.
* …

Changes necessary for the 12.1 branch

---

modules/ROOT/pages/appendices/release_notes.adoc
modules/ROOT/partials/nav.adoc

References: https://github.com/owncloud/docs-main/pull/29 (Adding iOS and Android release notes)
Backport to 12.1 and 12.0

Remove release notes

---

.drone.star

These are the changes necessary to finalize the creation of the 12.2 branch.
* The 12.2 branch is already pushed and prepared and is included in the branch protection rules.
* When 12.2 is finally out, the 12.0 branch can be archived, see step 3 in [Create a New Version Branch](https://github.com/owncloud/docs-client-ios-app/blob/master/docs/new-version-branch.md)
* Note, that the 12.2 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in iOS is set. This means, that in the docs homepage, `latest` will point to 12.1 until the tag in iOS is set accordingly. When merging this PR, 12.0 will be dropped from the web.
* Note that this PR must be merged **before** the 12.2 tag in iOS is set to avoid a 404 for `latest`.
* Note …

Changes necessary for iOS 12.2

---

.drone.star

This are the changes necessary to enable IOS 12.3 in this repo.
The branch has already been created.
NO backport!

Changes necessary to enable IOS 12.3

---

.drone.star

This are the changes necessary to for the 12.4 branch. Note that it currently does not contain any content changes.
The next step is to do a small PR in the docs branch to enable the 12.4 branch for building docs.

Changes necessary for the 12.4 branch

---

.drone.star
docs/new-version-branch.md

These are the changes necessary to finalize the creation of the 12.5 branch.
* The 12.5 branch is already pushed, prepared and is included in the branch protection rules.
* Note that this PR can be merged at any time but:
* must be merged **before** applying content changes and
* **before** merging the docs PR to include this version.
* Post merging this, we need to backport all relevant changes created in master to 12.5
@mmattel @phil-davis

Changes necessary for 12.5
